# Generated by Django 3.0.8 on 2020-08-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('hive_id', models.AutoField(primary_key=True, serialize=False)),
                ('hive_number', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleus',
            fields=[
                ('nucleus_id', models.AutoField(primary_key=True, serialize=False)),
                ('nucleus_number', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('queen_id', models.AutoField(primary_key=True, serialize=False)),
                ('queen_name', models.CharField(max_length=100)),
                ('queen_added_date', models.DateField()),
                ('queen_removed_date', models.DateField(blank=True, null=True)),
                ('hive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Hive')),
            ],
        ),
        migrations.CreateModel(
            name='NucleusQueen',
            fields=[
                ('nucleus_queen_id', models.AutoField(primary_key=True, serialize=False)),
                ('queen_name', models.CharField(max_length=100)),
                ('queen_added_date', models.DateField()),
                ('queen_removed_date', models.DateField(blank=True, null=True)),
                ('nucleus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Nucleus')),
            ],
        ),
        migrations.CreateModel(
            name='NucleusCheck',
            fields=[
                ('nucleus_check_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('observation', models.CharField(blank=True, max_length=2000)),
                ('nucleus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Nucleus')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=2000)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Location')),
            ],
        ),
        migrations.AddField(
            model_name='hive',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Location'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('opened_honey', models.DecimalField(decimal_places=3, max_digits=5)),
                ('closed_honey', models.DecimalField(decimal_places=3, max_digits=5)),
                ('opened_brood', models.DecimalField(decimal_places=3, max_digits=5)),
                ('closed_brood', models.DecimalField(decimal_places=3, max_digits=5)),
                ('drone_cell', models.DecimalField(decimal_places=3, max_digits=5)),
                ('queen_cell', models.IntegerField()),
                ('pollen_cell', models.DecimalField(decimal_places=3, max_digits=5)),
                ('observation', models.CharField(blank=True, max_length=2000)),
                ('hive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Hive')),
            ],
        ),
    ]
