# Generated by Django 3.0.8 on 2020-07-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beecheck', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
