# Generated by Django 3.0.8 on 2020-08-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beecheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=2000)),
                ('hive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Hive')),
            ],
        ),
    ]
