# Generated by Django 3.0.8 on 2020-08-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beecheck', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
