# Generated by Django 3.0.8 on 2020-08-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beecheck', '0002_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=2000)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beecheck.Location')),
            ],
        ),
    ]
