# Generated by Django 3.0.8 on 2020-08-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beecheck', '0003_auto_20200803_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
